name, surname  = str(input('Введіть ім\'я: ')), str(input('Введіть прізвище: '))
phone_number = str(input('Введіть номер телефону: '))
street, building_number, flat_number, city = str(input('Введіть вулицю: ')),  str(input('Введіть номер будинку: ')), str(input('Введіть номер квартири: ')), str(input('Введіть назву міста: '))
index, country = str(input('Введіть поштовий індекс: ')), str(input('Введіть країну: '))
print(f'{name} {surname}')
print(f'{phone_number}')
print(f'Str. {street}, {building_number}, ap. {flat_number}, {city}')
print(f'{index}')
print(f'{country}')